import Project1 from "../img/projeto-1.gif"
import Project2 from "../img/projeto-2.gif"
import Project3 from "../img/projeto-3.gif"
import Project4 from "../img/projeto-4.gif"
import Project5 from "../img/projeto-5.gif"
import { AiFillGithub } from 'react-icons/ai';
import { BsGlobe2 } from 'react-icons/bs';

export const projects = [
    { id: 1, name: "SPA IBGE API", img: Project2, description: "Aplicação em SPA que consume a API do IBGE. Tem a finalidade de fazer busca de estados e municípios através de um select, e após selecionar ou digitar os dois campos vai exibir na tela as informações dos distritos, da mesorregião, microrregião, UF e Região. Aplicação utiliza", technologies: "Redux, React, Javascript, Styled Components, Redux toolkit, Redux thunk e Fetch API", link: { github: "https://github.com/JoaoJorgedosAnjos/spa-ibge-api", page: "https://spa-ibge-api.vercel.app/" }, icon: { github: <AiFillGithub />, page: <BsGlobe2 /> } },
    { id: 2, name: "Poke API", img: Project1, description: "A aplicação em SPA que tem a finalidade de exibir uma lista de 10 Pokémon por página, com sua imagem, número e nome, com um total de 1124 Pokémon. Ao clicar em algum Pokémon da lista, o usuário será redirecionado para uma página com a arte oficial do Pokémon, e outras informações como o tipo, habilidades e movimentos.Aplicação utiliza", technologies: "React, Fetch API, Context API e Styled Components", link: { github: "https://github.com/JoaoJorgedosAnjos/pokedex-api", page: "https://pokedex-api-rho.vercel.app/" }, icon: { github: <AiFillGithub />, page: <BsGlobe2 /> } },
    { id: 3, name: "GitHub API", img: Project3, description: "Simulação de novas funções implantadas no projetos. A aplicação retorna nome do usuário, foto do peril, número de seguidores e de pessoas que está seguindo, eventos, quantidades de forks e várias outras informações da Github API. Tecnologias utlizadas no projeto", technologies: "HTML, CSS, Javascript e Fetch API", link: { github: "https://github.com/JoaoJorgedosAnjos/fetch-github-api", page: "https://joaojorgedosanjos.github.io/fetch-github-api/" }, icon: { github: <AiFillGithub />, page: <BsGlobe2 /> } },
    { id: 4, name: "Mini Portifólio", img: Project4, description: "O mini portifólio foi um projeto criado para mostrar algumas informações do usuário como redes sociais e uma breve apresentação sobre o mesmo, descrevendo curiosidades e informações pessoais. O projeto foi criado durante a Dev Week, projeto do canal Dev em Dobro. Tecnologias utlizadas no projeto", technologies: "HTML, CSS e Javascript", link: { github: "https://github.com/JoaoJorgedosAnjos/mini-portifolio", page: "https://joaojorgedosanjos.github.io/mini-portifolio/" }, icon: { github: <AiFillGithub />, page: <BsGlobe2 /> } },
    { id: 5, name: "News Homepage", img: Project5, description: "Projeto do Frontend Mentor. O desafio consiste em construir um website homepage que seja o mais parecido possível com o design proposto.Tecnologias utlizadas no projeto", technologies: "HTML e CSS", link: { github: "https://github.com/JoaoJorgedosAnjos/news-homepage", page: "https://joaojorgedosanjos.github.io/news-homepage/" }, icon: { github: <AiFillGithub />, page: <BsGlobe2 /> } }
]